bind_address = "127.0.0.1"
bind_port = 3000
debug = "Debug"
db_path = "comments.sqlite"
enable_email_notifications = true
email_notify_address = "admin@example.com"
email_sender_address = "tinycomments@yourserver.example.com"
email_sender_name = "Tinycomments"
email_smtp_host = "yoursmtphost.example.com"
#email_smtp_user = "tinycomments"
#email_smtp_pass = "YOUR_PASSWORD"
